/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nagyi.vedelmi.szoftver;

/**
 *
 * @author Pesta
 */
public class NagyiErtesitoAblakUI extends javax.swing.JFrame {

    /**
     * Creates new form NagyiErtesitoAblakUI
     */
    public NagyiErtesitoAblakUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ertesitesiCimke = new javax.swing.JLabel();
        bezarasGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        ertesitesiCimke.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ertesitesiCimke.setForeground(new java.awt.Color(255, 0, 0));
        ertesitesiCimke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ertesitesiCimke.setText("Értesítő");
        ertesitesiCimke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ertesitesiCimke.setPreferredSize(new java.awt.Dimension(800, 600));

        bezarasGomb.setText("OK!");
        bezarasGomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bezarasGombMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(ertesitesiCimke, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(bezarasGomb)))
                .addContainerGap(934, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ertesitesiCimke, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bezarasGomb)
                .addContainerGap(980, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bezarasGombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bezarasGombMouseClicked
        this.dispose();        
    }//GEN-LAST:event_bezarasGombMouseClicked
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bezarasGomb;
    private javax.swing.JLabel ertesitesiCimke;
    // End of variables declaration//GEN-END:variables

    public void setUzenet(String uzenet) {
        ertesitesiCimke.setText(uzenet);
    }
}
